# bases:
# - ../../base

# patches:
#  - replicas.yaml

# configMapGenerator:
# - name: mykustom-map
#   env: config.properties

bases:
  - ../../base

patches:
  - path: replicas.yaml
    target:
      kind: Deployment
      name: kustom-kustomwebapp-v1   # Base Deployment name with prefix/suffix applied

configMapGenerator:
  - name: mykustom-map
    env: config.properties
